language: java
sudo: required
jdk:
- oraclejdk8
before_install:
- echo "deb http://integration.stg.ortussolutions.com/artifacts/debs/noarch /" > commandbox.list
- sudo mv commandbox.list /etc/apt/sources.list.d/commandbox.list
- sudo apt-get update
install:
- sudo apt-get install -q -y --force-yes commandbox
- box install
before_script:
- chmod +x test
script:
- "./test"
